openapi: 3.0.1
################################################################################
#                              API Information                                 #
################################################################################
info:
  title: Instagram API
  description: The Instagram Private API in OpenAPI specs.v3.0
  version: 0.0.1
################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
servers:
- url: https://i.instagram.com/api/v1
  description: The private API of Instagram
  # variables:
  #   base: 
  #     default: api
  #   version: 
  #     enum: 
  #       - v1
  #       - v2
  #     default: v2
################################################################################
#                              Paths (Endpoints)                               #
################################################################################
paths:
  /accounts/login:
    post:
      tags: 
      - Auth
      summary: Login user to Instagram
      description: Login to Instagram with username/password
      responses:
        200:
          description: Successfully login the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/self:
    get:
      tags:
      - User
      summary: User Profile
      description: The User Profile endpoint returns information about the Instagram user
        that has authorized with the application.
      responses:
        200:
          description: Profile information for a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  

################################################################################
#                                 Definitions                                  #
################################################################################
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fields:
          type: string