################################################################################
#                                 Parameters                                   #
################################################################################
# Documentation link
# https://swagger.io/docs/specification/describing-parameters/

#-----------------
# Path params
#-----------------

#-----------------
# Query params
#-----------------
username:
  in: query
  name: username
  schema:
    type: string
  required: true
  description: >
    the username (or nickname)
#-----------------
password:
  in: query
  name: password
  schema:
    type: string
  required: true
  description: >
    the password to use for authentication

#-----------------
# Header params
#-----------------
ua:
  in: header
  name: User-Agent
  schema:
    type: string
  required: true
  description: >
    the password to use for authentication

#-----------------
# Cookie params
#-----------------